[package]
name = "my_first_package"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]

[addresses]
my_first_package = "0x0"

[dev-dependencies]

[dev-addresses]

